# Generated by Django 6.0.5 on 2026-05-16 14:50

from django.conf import settings
from django.db import migrations, models


def remove_duplicate_job_reminders(apps, schema_editor):
    Alert = apps.get_model("alerts", "Alert")

    duplicate_groups = (
        Alert.objects.filter(
            alert_type="JOB_REMINDER",
            job__isnull=False,
        )
        .values("owner_id", "job_id", "alert_type")
        .annotate(total=models.Count("id"))
        .filter(total__gt=1)
    )

    for group in duplicate_groups:
        reminders = Alert.objects.filter(
            owner_id=group["owner_id"],
            job_id=group["job_id"],
            alert_type=group["alert_type"],
        ).order_by("is_read", "-created_at", "-id")

        reminder_to_keep = reminders.first()

        if reminder_to_keep:
            reminders.exclude(id=reminder_to_keep.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_owner'),
        ('jobs', '0002_job_owner'),
        ('materials', '0002_material_owner'),
        ('planning', '0002_calendarevent_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_job_reminders, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(condition=models.Q(('alert_type', 'JOB_REMINDER'), ('job__isnull', False)), fields=('owner', 'job', 'alert_type'), name='unique_job_reminder_per_job_owner'),
        ),
    ]
