# Generated by Django 6.0.5 on 2026-05-09 07:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptado'), ('REJECTED', 'Rechazado'), ('CONVERTED', 'Convertido en trabajo')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='IVA (%)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Importe IVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Cantidad')),
                ('unit', models.CharField(default='unidad', max_length=50, verbose_name='Unidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Importe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budgets.budget', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Concepto de presupuesto',
                'verbose_name_plural': 'Conceptos de presupuesto',
                'ordering': ['id'],
            },
        ),
    ]
