# Generated by Django 6.0.5 on 2026-05-09 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('event_type', models.CharField(choices=[('VISIT', 'Visita'), ('JOB', 'Trabajo'), ('REMINDER', 'Recordatorio')], default='JOB', max_length=20, verbose_name='Tipo de evento')),
                ('start_at', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('end_at', models.DateTimeField(verbose_name='Fecha y hora de fin')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Ubicación')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('PLANNED', 'Planificado'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='PLANNED', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='jobs.job', verbose_name='Trabajo')),
            ],
            options={
                'verbose_name': 'Evento de calendario',
                'verbose_name_plural': 'Eventos de calendario',
                'ordering': ['start_at'],
            },
        ),
    ]
