# Generated by Django 6.0.5 on 2026-05-09 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora de fin')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PLANNED', 'Planificado'), ('IN_PROGRESS', 'En progreso'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('budget', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job', to='budgets.budget', verbose_name='Presupuesto')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
