# Generated by Django 6.0.5 on 2026-05-09 08:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('material_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo')),
                ('provider', models.CharField(blank=True, max_length=150, verbose_name='Proveedor')),
                ('quantity_available', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cantidad disponible')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Stock mínimo')),
                ('unit', models.CharField(default='unidad', max_length=50, verbose_name='Unidad de medida')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio unitario')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('LOW_STOCK', 'Stock bajo'), ('OUT_OF_STOCK', 'Agotado')], default='AVAILABLE', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad consumida')),
                ('consumption_date', models.DateField(verbose_name='Fecha de consumo')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_consumptions', to='jobs.job', verbose_name='Trabajo')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='materials.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Consumo de material',
                'verbose_name_plural': 'Consumos de materiales',
                'ordering': ['-consumption_date', '-created_at'],
            },
        ),
    ]
