# Generated by Django 6.0.5 on 2026-05-16 10:37

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_start_time', models.TimeField(default=datetime.time(9, 0), verbose_name='Hora de inicio por defecto')),
                ('default_end_time', models.TimeField(default=datetime.time(18, 0), verbose_name='Hora de fin por defecto')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name='Stock bajo por defecto')),
                ('upcoming_job_days', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Dias de aviso previo para trabajos proximos')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Configuracion de usuario',
                'verbose_name_plural': 'Configuraciones de usuario',
            },
        ),
    ]
